-- ============================================================
-- 키품타 (KPT) — 전체 설치 스크립트
-- 처음부터 끝까지 순서대로 실행. 여러 번 실행해도 안전합니다.
-- ============================================================


-- ------------------------------------------------------------
-- 1. 스키마 · 테이블
-- ------------------------------------------------------------

CREATE SCHEMA IF NOT EXISTS kiwoom;

CREATE TABLE IF NOT EXISTS kiwoom.user_info (
    user_id     UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    nickname    TEXT UNIQUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS kiwoom.study_history (
    history_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    subject     TEXT NOT NULL,
    start_time  TIMESTAMPTZ NOT NULL,
    end_time    TIMESTAMPTZ
);

ALTER TABLE kiwoom.study_history
    ADD COLUMN IF NOT EXISTS study_minutes INT;


-- ------------------------------------------------------------
-- 2. 제약 · 인덱스
-- ------------------------------------------------------------

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'study_history_time_order'
    ) THEN
        ALTER TABLE kiwoom.study_history
            ADD CONSTRAINT study_history_time_order
            CHECK (end_time IS NULL OR end_time > start_time);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'user_info_nickname_len'
    ) THEN
        ALTER TABLE kiwoom.user_info
            ADD CONSTRAINT user_info_nickname_len
            CHECK (nickname IS NULL OR char_length(nickname) BETWEEN 2 AND 12);
    END IF;
END $$;

-- 한 사용자당 진행 중 세션은 하나만
CREATE UNIQUE INDEX IF NOT EXISTS study_history_one_open
    ON kiwoom.study_history (user_id)
    WHERE end_time IS NULL;

CREATE INDEX IF NOT EXISTS study_history_user_time
    ON kiwoom.study_history (user_id, start_time DESC);


-- ------------------------------------------------------------
-- 3. 신규 계정 → user_info 행 자동 생성
-- ------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = kiwoom, pg_temp
AS $$
BEGIN
    INSERT INTO kiwoom.user_info (user_id)
    VALUES (NEW.id)
    ON CONFLICT (user_id) DO NOTHING;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;

CREATE TRIGGER on_auth_user_created
AFTER INSERT ON auth.users
FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- 트리거 생기기 전에 만들어진 계정 백필
INSERT INTO kiwoom.user_info (user_id)
SELECT id FROM auth.users
ON CONFLICT (user_id) DO NOTHING;


-- ------------------------------------------------------------
-- 4. 통계 뷰
--    자정 넘긴 세션은 시작일 기준. 완료된 세션만 집계.
--    분 단위는 저장값이 아니라 시각 차이로 계산해 어긋날 수 없게 함.
-- ------------------------------------------------------------

CREATE OR REPLACE VIEW kiwoom.daily_stats AS
SELECT
    user_id,
    (start_time AT TIME ZONE 'Asia/Seoul')::date          AS study_date,
    subject,
    SUM(EXTRACT(EPOCH FROM (end_time - start_time)) / 60)::int AS study_minutes,
    COUNT(*)                                             AS session_count
FROM kiwoom.study_history
WHERE end_time IS NOT NULL
GROUP BY user_id, (start_time AT TIME ZONE 'Asia/Seoul')::date, subject;


-- ------------------------------------------------------------
-- 5. 개인 통계 RPC
--    p_days = NULL 이면 전체 누적
-- ------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.get_my_stats(p_days INT DEFAULT NULL)
RETURNS TABLE (
    study_date    DATE,
    subject       TEXT,
    study_minutes INT,
    session_count BIGINT
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = kiwoom, pg_temp
AS $$
    SELECT d.study_date, d.subject, d.study_minutes, d.session_count
    FROM kiwoom.daily_stats d
    WHERE d.user_id = auth.uid()
      AND (p_days IS NULL
           OR d.study_date >= (now() AT TIME ZONE 'Asia/Seoul')::date
                              - make_interval(days => p_days - 1))
    ORDER BY d.study_date, d.subject;
$$;


-- ------------------------------------------------------------
-- 6. 비교 통계 RPC
--    percentile: 1에 가까울수록 상위
-- ------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.get_leaderboard(p_days INT DEFAULT NULL)
RETURNS TABLE (
    rank          BIGINT,
    nickname      TEXT,
    study_minutes INT,
    session_count BIGINT,
    percentile    NUMERIC
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = kiwoom, pg_temp
AS $$
    WITH totals AS (
        SELECT
            d.user_id,
            SUM(d.study_minutes)::int AS total_minutes,
            SUM(d.session_count)      AS total_sessions
        FROM kiwoom.daily_stats d
        WHERE p_days IS NULL
           OR d.study_date >= (now() AT TIME ZONE 'Asia/Seoul')::date
                              - make_interval(days => p_days - 1)
        GROUP BY d.user_id
    )
    SELECT
        RANK() OVER (ORDER BY t.total_minutes DESC)           AS rank,
        COALESCE(u.nickname, '(닉네임 없음)')                  AS nickname,
        t.total_minutes                                       AS study_minutes,
        t.total_sessions                                      AS session_count,
        ROUND(PERCENT_RANK() OVER (ORDER BY t.total_minutes)::numeric, 2) AS percentile
    FROM totals t
    JOIN kiwoom.user_info u ON u.user_id = t.user_id
    ORDER BY t.total_minutes DESC;
$$;


-- ------------------------------------------------------------
-- 7. 권한
-- ------------------------------------------------------------

GRANT USAGE ON SCHEMA kiwoom TO authenticated;

GRANT SELECT, UPDATE ON kiwoom.user_info    TO authenticated;
GRANT SELECT, INSERT, UPDATE ON kiwoom.study_history TO authenticated;
GRANT SELECT ON kiwoom.daily_stats TO authenticated;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA kiwoom TO authenticated;

GRANT EXECUTE ON FUNCTION public.get_my_stats(INT)    TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_leaderboard(INT) TO authenticated;


-- ------------------------------------------------------------
-- 8. 예시 데이터
--    study_history가 비어 있을 때만 들어갑니다.
--    날짜는 실행 시점 기준 상대 시각이라 언제 돌려도 최근 데이터가 됩니다.
-- ------------------------------------------------------------

INSERT INTO kiwoom.study_history (user_id, subject, start_time, end_time, study_minutes)
SELECT
    b.user_id,
    (ARRAY['SQLD', '컴활', '파이썬', '금융투자분석사'])[b.subj_idx + 1],
    b.start_ts,
    b.start_ts + make_interval(mins => b.dur),
    b.dur
FROM (
    SELECT
        a.id AS user_id,
        (abs(hashtext(a.id::text || d::text)) % 4)        AS subj_idx,
        45 + (abs(hashtext(a.id::text || d::text || 'm')) % 150) AS dur,
        date_trunc('day', now() - make_interval(days => d))
            + make_interval(hours => 9 + (abs(hashtext(a.id::text || d::text || 'h')) % 11)) AS start_ts
    FROM auth.users a
    CROSS JOIN generate_series(1, 21) AS d
    WHERE (abs(hashtext(a.id::text || d::text || 'x')) % 10) < 7
) b
WHERE NOT EXISTS (SELECT 1 FROM kiwoom.study_history);


-- ------------------------------------------------------------
-- 9. 확인
-- ------------------------------------------------------------

SELECT a.email, u.nickname, COUNT(h.history_id) AS sessions
FROM auth.users a
LEFT JOIN kiwoom.user_info u    ON u.user_id = a.id
LEFT JOIN kiwoom.study_history h ON h.user_id = a.id
GROUP BY a.email, u.nickname
ORDER BY a.email;
